// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Solution 1
let limit = 4000000;
let sum = 0;
let a = 1;
let b = 1;

while (b < limit) {
  if (b % 2 === 0) sum += b;
  let h = a + b;
  a = b;
  b = h;
}

console.log(sum);

//Solution 2
//Idea is to get rid of the testing for even values.
//It is easy to prove that every third Fibonacci number is even.
//  1  1  2  3  5  8  13  21  34  55  89  144 ...
//  a  b  c  a  b  c  a   b   c   a   b   c

let limit = 4000000;
let sum = 0;
let a = 1;
let b = 1;
let c = a + b;

while (c < limit) {
  sum += c;
  a = b + c;
  b = c + a;
  c = a + b;
}

console.log(sum);
