// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Solution 1 by using array
const temp_arr = [1, 2];
let arr_length = temp_arr.length;
let result = 2;

while (temp_arr[arr_length - 1] < 4000000) {
  let newFibo = temp_arr[arr_length - 2] + temp_arr[arr_length - 1];
  temp_arr.push(newFibo);
  arr_length = temp_arr.length;
  if (newFibo % 2 === 0) {
    result += newFibo;
  }
}

console.log(result);

//Solution 2 without array
let prevNum = 1;
let currentNum = 2;
let newFibo = 3;
let result = 2;

while (newFibo < 4000000) {
  if (newFibo % 2 === 0) {
    result += newFibo;
  }
  prevNum = currentNum;
  currentNum = newFibo;
  newFibo = prevNum + currentNum;
}

console.log(result);
